services:
  backend:
    build:
      context: ./backend
    container_name: eiatube_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MEDIA_BASE_URL=
    volumes:
      - eiatube_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: eiatube_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  eiatube_uploads:
